language: go
os:
  - linux
go:
  - 1.7
services:
  - docker
install:
  - sudo apt-get install -qq upx
  - go get github.com/Sirupsen/logrus
  - go get github.com/getblank/wango
  - go get github.com/spf13/cobra
  - go get github.com/ivahaev/verlog
  - chmod +x sender.sh
script: go get -t -v ./...
after_success:
  - go build -ldflags "-X main.buildTime=`date +%Y-%m-%d:%H:%M:%S` -X main.gitHash=`git rev-parse --short HEAD`"
  - echo ${TRAVIS_BRANCH}
  - echo ${TRAVIS_TAG}
  - if [[ ${TRAVIS_TAG} ]]; then
      upx --best blank-fs;
    fi
deploy:
  provider: releases
  api_key: $TOKEN
  file: ./blank-fs
  on:
    tags: true
    repo: sclif13/blank-fs
